steps:
  - name: python
    script: |
      #!/bin/bash
      cd pipeline
      python -m venv venv && . venv/bin/activate
      pip install -U -r requirements.txt
      python pipeline.py
  - name: gcr.io/cloud-builders/gsutil # get skaffold build cache
    args: ['cp', "pipeline/pipeline.json", '$_PIPELINE_BUCKET/']
  - name: python
    script: |
      #!/bin/bash
      cd pipeline && . venv/bin/activate
      python submit_pipeline_job.py
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - trigger_func
      - --region=us-central1
      - --source=pipeline/pipeline_trigger_function/
options:
  logging: CLOUD_LOGGING_ONLY